import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Button from "@mui/material/Button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="banner">
          <div className="overlay pl-1 ">
            <h2 className="pt-1 font-lg">Welcome to</h2>
            <h1 className="font-xl">Hotel Management System</h1>
            <div className="mt-lg">
              <Link href="/view/hotel">
                <Button sx={{ p: 2, mr: 2 }} variant="contained" size="large">
                  Explore Hotels
                </Button>
              </Link>
              <Link href="/view/booking">
                <Button sx={{ p: 2, mr: 2 }} variant="contained" size="large">
                  Expore Booking
                </Button>
              </Link>
              <Link href="/view/guest">
                <Button sx={{ p: 2, mr: 2 }} variant="contained" size="large">
                  Explore Guest
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
